Style/RedundantReturn:
  Enabled: false

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/LineLength:
  Max: 80

Layout/ExtraSpacing:
  Enabled: false

Layout/SpaceAroundOperators:
  Enabled: false

Naming/VariableNumber:
  Enabled: False

Style/PerlBackrefs:
  Enabled: False

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Style/FormatStringToken:
  Enabled: False
